### ISSUE TITLE
Is there an example for how to use this extension?

### ISSUE THREAD

**Issue by pluto-the-lost** [osscar-org/jupyterlab-hide-code#2]
Hi,

Thanks for the extension, a function of hiding code blocks is really what I want. But I did not see any difference after installing this extension. Could the author record a vedio or a gif to explain how to do the hiding thing?

Thank you

**Comment by ZviBaratz** [comment]
Hi @pluto-the-lost, the extension creates an eye icon at the top right corner, next to the kernel's name. Pressing the icon will toggle the cell's input visibility. 
@dou-du can this issue be closed? Would you like a PR to add a gif to the README?

**Comment by dou-du** [comment]
Sorry, just notice this issue. Thank @ZviBaratz for the explanation. Yes, if you have a gif, please make a PR and I will merge it. Thanks a lot!
