### ISSUE TITLE
Support for JupyterLab 3

### ISSUE THREAD

**Issue by ZviBaratz** [osscar-org/jupyterlab-hide-code#3]
Hi @dou-du, thanks for sharing this useful extension. I've grown used to having this functionality with normal jupyter notebooks, it seems like it's not as popular among jupyter lab users. 
Unfortunately, it seems like the extension isn't updated for jupyter lab~=3.0, I was wondering whether you have any plans on updating it.
Thank you and all the best!

**Comment by dou-du** [comment]
> Hi @dou-du, thanks for sharing this useful extension. I've grown used to having this functionality with normal jupyter notebooks, it seems like it's not as popular among jupyter lab users.
> Unfortunately, it seems like the extension isn't updated for jupyter lab~=3.0, I was wondering whether you have any plans on updating it.
> Thank you and all the best!

Thank you very much! I will start to update it next week and let you know when it is ready.

**Comment by dou-du** [comment]
> Hi @dou-du, thanks for sharing this useful extension. I've grown used to having this functionality with normal jupyter notebooks, it seems like it's not as popular among jupyter lab users.
> Unfortunately, it seems like the extension isn't updated for jupyter lab~=3.0, I was wondering whether you have any plans on updating it.
> Thank you and all the best!

The extension has been updated. The installation method has been changed to "PyPi". Please tell me if there is any problem for it. Thanks!
