### ISSUE TITLE
optionality to just hide and not run

### ISSUE THREAD

**Issue by GrazMir** [osscar-org/jupyterlab-hide-code#35]
Hi, 
if the notebook is quite heavy trigering a re-run every time you hide the input can be expensive.

**Comment by dou-du** [comment]
> Hi, if the notebook is quite heavy trigering a re-run every time you hide the input can be expensive.

Thanks for the suggestion. However, we aims at offering a simple and fast tool to check the running results.
Add this functionality will make this tool complex.
